name: fchecknew
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.4+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_gauges: any
  flutter_circular_text: "^0.3.1"
  video_player: any
  delayed_display: ^1.1.0



  syncfusion_flutter_pdf: any
  path_provider: any
  open_file: any
  esys_flutter_share: any
  carousel_slider: ^3.0.0
  url_launcher: ^6.0.9
  webview_flutter: ^2.0.10
  http: any
  shared_preferences: any




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.19.1

  flutter_secure_storage: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/icons/
    - assets/images/
    - assets/icons/dfgd.png
    - images/male.png
    - images/fcheck_app.png
    - images/female.png
    - images/guages.jpg
    - video/malev.mp4
    - video/femalev.mp4
    - images/brain.png
    - images/heart.png
    - images/kidny.png
    - images/larin.png
    - images/liver.png
    - images/lunce.png
    - images/smlin.png
    - images/stomack.png
    - images/indicator.png
    - images/heart1.png
    - images/color.png
    - images/colors.png
    - images/indicator1.png
    - images/1.jpg
    - images/splashScreen.jpg
    - images/loginback.jpg
    - images/appicon.png
    - images/details_heart.png
    - images/detailspage1.jpg
    - images/detailspage2.jpg
    - images/detailspage3.jpg
    - images/heartone.png
    - images/hearttwo.png
    - images/heartthree.png
    - images/largeintenstine.png
    - images/li_one.png
    - images/li_two.png
    - images/li_three.png
    - images/intenstine.png
    - images/in_one.png
    - images/in_two.png
    - images/in_three.png
    - images/lungs.png
    - images/lungs_one.png
    - images/lungs_two.png
    - images/lungs_three.png
    - images/cslider.png
    - images/brain_one.png
    - images/brain_two.png
    - images/brain_three.png
    - images/brain_four.png
    - images/liver_one.png
    - images/liver_two.png
    - images/liver_three.png
    - images/liver_four.png
    - images/stom_one.png
    - images/stom_two.png
    - images/stom_three.png
    - images/stom_four.png
    - images/lungsnew.png
    -  images/lungsnew1.png
    -  images/lungsnew2.png
    -  images/lungsnew3.png
    -  images/intesnew.png
    -  images/intesnew1.png
    -  images/intesnew2.png
    -  images/intesnew3.png
    -  images/liver1.png
    -  images/liver2.png
    -  images/liver3.png
    -  images/feonnaa_logo.png
    -  images/bmi.png
    -  images/health_tips.png
    -  images/contact.png
    -  images/chat.png
    -  images/appinfo.png
    -  images/logout.png
    -  images/fcheck.png
    - images/unw_im.png
    - images/nunw_im.png
    - images/hel_im.png
    - images/novw_im.png
    - images/ovw_im.png
    - images/obes_im.png
    - image_report/1.png
    - image_report/2.png
    - image_report/3.png
    - image_report/4.png
    - image_report/5.png
    - image_report/6.png
    - image_report/7.png
    - image_report/8.png
    - image_report/feonnaa_logo.png
    - image_new/fcheck_login.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
